version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: job_hunter_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - qdrant

  frontend:
    build:
      context: ./frontend-app
    container_name: job_hunter_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://backend:8000

  db:
    image: postgres:15
    container_name: job_hunter_db
    environment:
      POSTGRES_DB: jobhunter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: jobhunter-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  postgres_data:
  qdrant_storage: